name: 'publish docker'

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Dockerfile
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: true
        tags: |
          happy888888/weibotask:${{ github.event.inputs.version }}
          happy888888/weibotask:latest

    - name: Build Dockerfile-arm
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm/v7
        push: true
        tags: |
          happy888888/weibotask:arm-${{ github.event.inputs.version }}
          happy888888/weibotask:arm-latest

    - name: Build Dockerfile-arm64
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        push: true
        tags: |
          happy888888/weibotask:arm64-${{ github.event.inputs.version }}
          happy888888/weibotask:arm64-latest